# Generated by Django 5.2.6 on 2025-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammaMia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
    ]
