# Generated by Django 5.2.6 on 2025-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammaMia', '0002_pizza_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='masas/'),
        ),
    ]
